Added network create, remove and list functions

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -26,6 +26,9 @@ COMMANDS
     detach-disk - detach a disk device from a guest domain
     list        - list all domains, running and stopped
     remove      - delete a guest domain
+    net-create  - create and activate a network
+    net-remove  - remove and undefine a network
+    net-list    - list all networks
 
 EOF
 exit 0
@@ -59,6 +62,7 @@ function usage_subcommand ()
             printf "    -L          Location of VMs     (default: $HOME/virt/vms)\n"
             printf "    -m          Memory Size (MB)    (default: 1024)\n"
             printf "    -M          Mac address         (default: auto-assigned)\n"
+            printf "    -n          Network             (default: not filled in, when defined it is used instead of Bridge)"
             printf "    -p          Console port        (default: auto)\n"
             printf "    -s          Custom shell script\n"
             printf "    -t          Linux Distribution  (default: centos7)\n"
@@ -139,6 +143,59 @@ function usage_subcommand ()
             printf "\n"
             printf "DESCRIPTION\n"
             printf "    Lists all running and stopped guest domains.\n"
+            ;;
+        net-create)
+            printf "NAME\n"
+            printf "    $prog net-create\n"
+            printf "\n"
+            printf "DESCRIPTION\n"
+            printf "    Create a new network.\n"
+            printf "\n"
+            printf "COMMANDS\n"
+            printf "    help - show this help\n"
+            printf "\n"
+            printf "OPTIONS\n"
+            printf "    -a          Autostart           (default: false)\n"
+            printf "    -b          Bridge              (default: virbr0)\n"
+            printf "    -n          Network             (default: default)\n"
+            printf "    -s          DHCP start address  (default: 10.0.0.2) \n"
+            printf "    -e          DHCP end address    (default: 10.0.0.254)\n"
+            printf "    -M          Mac address         (default: auto-assigned)\n"
+            printf "    -A          IP address          (default: 10.0.0.1)\n"
+            printf "    -m          Netmask             (default: 255.255.255.0)\n"
+            printf "    -f          Forwarding mode     (default: nat)\n"
+            printf "    -d          Interface device    (default: none)\n"
+            printf "\n"
+            printf "FORWARDING MODES\n"
+            printf "    nat\n"
+            printf "    routed\n"
+            printf "    isolated\n"
+#            printf "    PCI passthrough\n"
+            printf "\n"
+            printf "EXAMPLE\n"
+            printf "    $prog net-create\n"
+            printf "        Creates a default network\n"
+            ;;
+        net-remove)
+            printf "NAME\n"
+            printf "    $prog net-remove\n"
+            printf "\n"
+            printf "DESCRIPTION\n"
+            printf "    Removes and undefines a network.\n"
+            printf "\n"
+            printf "COMMANDS\n"
+            printf "    help - show this help\n"
+            printf "\n"
+            printf "EXAMPLE\n"
+            printf "    $prog net-remove default\n"
+            printf "        Removes and undefines network default\n"
+            ;;
+        net-list)
+            printf "NAME\n"
+            printf "    $prog net-list\n"
+            printf "\n"
+            printf "DESCRIPTION\n"
+            printf "    List all active networks.\n"
             ;;
         *)
             printf "'$subcommand' is not a valid subcommand.\n"
@@ -534,12 +591,17 @@ _EOF_
         --target ${VMDIR}/${VMNAME} &>> ${VMNAME}.log && ok) \
         || die "Could not create storage pool."
 
-    # Add custom MAC Address if specified
-    if [ -z "${MACADDRESS}" ]
+    if [ -n "${NETWORK}" ]
     then
-        NETWORK_PARAMS="bridge=${BRIDGE},model=virtio"
+        NETWORK_PARAMS="network=${NETWORK},model=virtio"
     else
-        NETWORK_PARAMS="bridge=${BRIDGE},model=virtio,mac=${MACADDRESS}"
+        NETWORK_PARAMS="bridge=${BRIDGE},model=virtio"
+    fi
+
+    # Add custom MAC Address if specified
+    if [ -n "${MACADDRESS}" ]
+    then
+        NETWORK_PARAMS="${NETWORK_PARAMS},mac=${MACADDRESS}"
     fi
 
     if [ "${VERBOSE}" -eq 1 ]
@@ -681,6 +743,7 @@ function set_defaults ()
     IMAGEDIR=${HOME}/virt/images    # Directory to store images
     VMDIR=${HOME}/virt/vms          # Directory to store virtual machines
     BRIDGE=virbr0                   # Hypervisor bridge
+    NETWORK=""                      # Network name
     PUBKEY=""                       # SSH public key
     DISTRO=centos7                  # Distribution
     MACADDRESS=""                   # MAC Address
@@ -705,10 +768,10 @@ function set_custom_defaults ()
 function create ()
 {
     # Parse command line arguments
-    while getopts ":b:c:d:D:f:g:i:k:l:m:M:p:s:t:T:u:ahv" opt
+    while getopts ":b:c:d:D:f:g:i:k:l:m:M:n:p:s:t:T:u:ahv" opt
     do
         case "$opt" in
-            a ) AUTOSTART=${OPTARG} ;;
+            a ) AUTOSTART="${OPTARG}" ;;
             b ) BRIDGE="${OPTARG}" ;;
             c ) CPUS="${OPTARG}" ;;
             d ) DISK_SIZE="${OPTARG}" ;;
@@ -721,6 +784,7 @@ function create ()
             L ) VMDIR="${OPTARG}" ;;
             m ) MEMORY="${OPTARG}" ;;
             M ) MACADDRESS="${OPTARG}" ;;
+            n ) NETWORK="${OPTARG}" ;;
             p ) PORT="${OPTARG}" ;;
             s ) SCRIPTNAME="${OPTARG}" ;;
             t ) DISTRO="${OPTARG}" ;;
@@ -853,6 +917,119 @@ function attach-disk ()
 
 }
 
+function net-create ()
+{
+    # Set default values
+    NETWORK="default"
+    ADDRESS="10.0.0.1"
+    NETMASK="255.255.255.0"
+    DHCP_START="10.0.0.2"
+    DHCP_END="10.0.0.254"
+    FORWARDING="nat"
+
+    NETWORK_CONF="network.xml"
+
+    # Parse command line options
+    while getopts ":b:n:s:e:M:A:m:f:d:ahv" opt
+    do
+        case "$opt" in
+            a ) AUTOSTART="${OPTARG}" ;;
+            h ) usage ;;
+            v ) VERBOSE=1 ;;
+            b ) BRIDGE="${OPTARG}" ;;
+            n ) NETWORK="${OPTARG}" ;;
+            s ) DHCP_START="${OPTARG}" ;;
+            e ) DHCP_END="${OPTARG}" ;;
+            M ) MACADDRESS="${OPTARG}" ;;
+            A ) ADDRESS="$(OPTARG)" ;;
+            m ) NETMASK="${OPTARG}" ;;
+            f ) FORWARDING="${OPTARG}" ;;
+            d ) DEVICE="${OPTARG}" ;;
+            * ) die "Unsupported option. Run 'kvm-install-vm help net-create'." ;;
+        esac
+    done
+
+    shift $((OPTIND - 1))
+
+    # create the network.xml file
+    > ${NETWORK_CONF}
+    printf "<network>\n"                                              >> ${NETWORK_CONF}
+    printf "  <name>${NETWORK}</name>\n"                              >> ${NETWORK_CONF}
+    if [ "${FORWARDING}" != "isolated" ]
+    then
+        if [ -n "${DEVICE}" ]
+        then
+            printf "  <forward dev='eth1' mode='${FORWARDING}'>\n"            >> ${NETWORK_CONF}
+            printf "    <interface dev='eth1'/>\n"                            >> ${NETWORK_CONF}
+            printf "  </forward>\n"                                           >> ${NETWORK_CONF}
+        else
+            printf "  <forward mode='${FORWARDING}'/>\n"                      >> ${NETWORK_CONF}
+        fi
+    fi
+    printf "  <bridge name='${BRIDGE}' stp='on' delay='0'/>\n"        >> ${NETWORK_CONF}
+    printf "  <mac address='${MACADDRESS}'/>\n"                       >> ${NETWORK_CONF}
+    printf "  <domain name='${NETWORK}'/>\n"                          >> ${NETWORK_CONF}
+    printf "  <ip address='${ADDRESS}' netmask='${NETMASK}'>\n"       >> ${NETWORK_CONF}
+    printf "    <dhcp>\n"                                             >> ${NETWORK_CONF}
+    printf "      <range start='${DHCP_START}' end='${DHCP_END}'/>\n" >> ${NETWORK_CONF}
+    printf "    </dhcp>\n"                                            >> ${NETWORK_CONF}
+    printf "  </ip>\n"                                                >> ${NETWORK_CONF}
+    printf "</network>\n"                                             >> ${NETWORK_CONF}
+
+    outputn "Creating the network ${NETWORK}"
+    virsh net-define \
+        ${NETWORK_CONF} &>> ${NETWORK}.log \
+        && ok \
+        || die "Could not create network."
+
+    outputn "Starting network ${NETWORK}"
+    virsh net-start \
+        ${NETWORK} > /dev/null 2>&1 \
+        && ok \
+        || die "Could not start network."
+
+    if ${AUTOSTART}
+    then
+        outputn "Autostarting the network ${NETWORK}"
+        virsh net-autostart \
+            ${NETWORK} > /dev/null 2>&1 \
+            && ok \
+            || die "Could not autostart network."
+    fi
+}
+
+function net-remove ()
+{
+    # Parse command line arguments
+    while getopts ":nv" opt
+    do 
+        case "$opt" in
+            v) VERBOSE=1 ;;
+            h) usage ;;
+            *) die "Unsupported option. Run 'kvm-install-vm help net-remove'." ;;
+        esac
+    done
+
+    if [ "$#" != 1 ]
+    then
+        printf "Please speficy a single network to remove.\n"
+        printf "Run 'kvm-install-vm help net-remove' for usage.\n"
+        exit 1
+    else
+        NETWORK=$1
+    fi
+
+    outputn "Destroying network ${NETWORK}"
+    virsh net-destroy ${NETWORK} > /dev/null 2>&1 \
+        && ok \
+        || yellow "(network is not active.)"
+
+    outputn "Undefining netowrk ${NETWORK}"
+    virsh net-undefine ${NETWORK} > /dev/null 2>&1 \
+        && ok \
+        || die "Could not undefine network."
+}
+
 #--------------------------------------------------
 # Main
 #--------------------------------------------------
@@ -867,7 +1044,7 @@ case "${subcommand}" in
     help)
         if [[ "${1:-none}" == "none" ]]; then
             usage
-        elif [[ "$1" =~ ^create$|^remove$|^list$|^attach-disk$ ]]; then
+        elif [[ "$1" =~ ^create$|^remove$|^list$|^attach-disk|^net-create|^net-remove|^net-list$ ]]; then
             usage_subcommand "$1"
         else
             printf "'$1' is not a valid subcommand.\n\n"
@@ -878,7 +1055,11 @@ case "${subcommand}" in
         virsh list --all
         exit 0
         ;;
-    create|remove|attach-disk|remove-disk)
+    net-list)
+        virsh net-list --all
+        exit 0
+        ;;
+    create|remove|attach-disk|remove-disk|net-create|net-remove)
         if [[ "${1:-none}" == "none" ]]; then
             usage_subcommand "${subcommand}"
         elif [[ "$1" =~ ^help$ ]]; then
