Don't use virt-resize on ubuntu1804

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -484,11 +484,18 @@ _EOF_
     if $RESIZE_DISK
     then
         outputn "Resizing the disk to $DISK_SIZE"
-        qemu-img create -f qcow2 \
-            -o preallocation=metadata $DISK.new $DISK_SIZE &>> ${VMNAME}.log \
-            && virt-resize --quiet --expand /dev/sda1 $DISK $DISK.new &>> ${VMNAME}.log \
-            && (mv $DISK.new $DISK && ok) \
-            || die "Could not resize disk."
+		if [ "${DISTRO}" = "ubuntu1804" ]
+        then
+            qemu-img resize $DISK $DISK_SIZE &>> ${VMNAME}.log \
+                && ok \
+                || die "Could not resize disk."
+		else
+			qemu-img create -f qcow2 \
+				-o preallocation=metadata $DISK.new $DISK_SIZE &>> ${VMNAME}.log \
+				&& virt-resize --quiet --expand /dev/sda1 $DISK $DISK.new &>> ${VMNAME}.log \
+				&& (mv $DISK.new $DISK && ok) \
+				|| die "Could not resize disk."
+		fi
     fi
 
     # Create CD-ROM ISO with cloud-init config
