Added support for mkisofs to generate cloud-init image.

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -422,11 +422,18 @@ _EOF_
 
     # Create CD-ROM ISO with cloud-init config
     outputn "Generating ISO for cloud-init"
-    genisoimage -output $CI_ISO \
-        -volid cidata \
-        -joliet -r $USER_DATA $META_DATA &>> ${VMNAME}.log \
-        && ok \
-        || die "Could not generate ISO."
+    if [ `which genisoimage &>/dev/null` ]
+    then
+        genisoimage -output $CI_ISO \
+            -volid cidata \
+            -joliet -r $USER_DATA $META_DATA &>> ${VMNAME}.log \
+            && ok \
+            || die "Could not generate ISO."
+    else
+        mkisofs -o $CI_ISO -V cidata -J -r $USER_DATA $META_DATA &>> ${VMNAME}.log \
+            && ok \
+            || die "Could not generate ISO."
+    fi
 
     if [ "${VERBOSE}" -eq 1 ]
     then
