Removed hardcoded options.
Added options for setting:
  - vCPUs
  - Memory
  - Disk Size
  - Distribution
  - Local image directory
  - SSH pubkey
  - Virtual bridge

diff --git a/virt-install-centos b/virt-install-centos
--- a/virt-install-centos
+++ b/virt-install-centos
@@ -1,129 +1,297 @@
 #!/bin/bash
 
-# Take one argument from the commandline: VM name
-if ! [ $# -eq 1 ]; then
-    echo "Usage: $0 <node-name>"
-    exit 1
+# Set program name variable
+prog=$0
+
+function usage {
+    echo "usage: $prog [OPTIONS] [-n vmname] [-r vmname]"
+    echo ""
+    echo "OPTIONS"
+    echo "  -c          Number of vCPUs     (default: 1)"
+    echo "  -m          Memory Size (MB)    (default: 1024)"
+    echo "  -d          Disk Size (GB)      (default: 10)"
+    echo "  -t          Linux distribution  (default: centos7)"
+    echo "  -i          Location of Images  (default: $HOME/virt/images)"
+    echo "  -k          SSH public key      (default: $HOME/.ssh/id_rsa.pub)"
+    echo "  -b          Bridge              (default: virbr0)"
+    echo "  -h          Display help"
+    echo "  -n vmname   Name of VM to create"
+    echo "  -r vmname   Name of VM to delete"
+    echo ""
+    echo "DISTRIBUTIONS"
+    echo " - centos7"
+    echo " - centos6"
+    echo " - debian8"
+    echo ""
+    echo "EXAMPLES"
+    echo ""
+    echo "Create VM with default params:"
+    echo "  $prog -n foo"
+    echo ""
+    echo "Create VM with custom params:"
+    echo "  $prog -c 2 -m 2048 -d 20 -n foo"
+    echo ""
+    echo "Remove (destroy and undefine) a VM:"
+    echo "  $prog -r foo"
+}
+
+# Reset OPTIND
+OPTIND=1
+
+#--------------------------------------------------
+# Defaults are set here.
+# Override using command line arguments.
+#--------------------------------------------------
+
+CPUS=1                          # Number of virtual CPUs
+MEMORY=1024                     # Amount of RAM in MB
+DISK_SIZE=10                    # Disk Size in GB
+RESIZE_DISK=false               # Resize disk (boolean)
+IMAGEDIR=${HOME}/virt/images    # Directory to store images
+BRIDGE=virbr0                   # Hypervisor bridge
+PUBKEY=${HOME}/.ssh/id_rsa.pub  # SSH public key
+DISTRO=centos7                  # Distribution
+
+#--------------------------------------------------
+# Parse command line arguments
+#--------------------------------------------------
+
+while getopts ":c:m:d:t:i:k:b:n:r:h" opt; do
+    case "$opt" in
+        c   ) CPUS="${OPTARG}" ;;
+        m   ) MEMORY="${OPTARG}" ;;
+        t   ) DISTRO="${OPTARG}" ;;
+        i   ) IMAGEDIR="${OPTARG}" ;;
+        n   ) VMNAME="${OPTARG}" ;;
+        k   ) PUBKEY="${OPTARG}" ;;
+        b   ) BRIDGE="${OPTARG}" ;;
+        r   ) VMDEL="${OPTARG}" ;;
+        d   )
+            if [ "${OPTARG}" -gt ${DISK_SIZE} ]; then
+                DISK_SIZE="${OPTARG}G"
+                RESIZE_DISK=true
+            else
+                DISK_SIZE="${DISK_SIZE}G"
+            fi
+            ;;
+        h|* ) usage; exit 1 ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+# Can't specify both -n and -r together
+if [ ! -z "${VMNAME+x}" ] && [ ! -z "${VMDEL+x}" ]
+then
+    echo "-n and -r are mutually exclusive."
+    exit 2
 fi
 
-# Check if domain already exists
-virsh dominfo $1 > /dev/null 2>&1
-if [ "$?" -eq 0 ]; then
-    echo -n "[WARNING] $1 already exists.  "
-    read -p "Do you want to overwrite $1 (y/[N])? " -r
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
-        echo "$(date -R) Destroying the $1 domain..."
-        # Remove domain with the same name
-        virsh destroy $1 >> $1.log 2>&1
-        virsh undefine $1 >> $1.log 2>&1
+function delete_vm {
+    VM=$1
+    echo "$(date -R) Destroying ${VM} domain..."
+    virsh destroy ${VM} > /dev/null 2>&1
+    echo "$(date -R) Destroying ${VM} storage pool..."
+    virsh pool-destroy ${VM} > /dev/null 2>&1
+    echo "$(date -R) Undefining ${VM} storage pool..."
+    virsh pool-undefine ${VM} > /dev/null 2>&1
+    echo "$(date -R) Undefining ${VM} domain..."
+    virsh undefine ${VM} > /dev/null 2>&1
 
-        echo "$(date -R) Destroying the $1 storage pool..."
-        # Remove the associated pool
-        virsh pool-destroy $1 >> $1.log 2>&1
-        virsh pool-undefine $1 >> $1.log 2>&1
+    echo "$(date -R) Deleting ${VM} files..."
+    rm -rf $IMAGEDIR/$VM
+}
+
+# Delete VM if -r is set
+if [ ! -z "${VMDEL+x}" ]
+then
+    delete_vm ${VMDEL}
+    exit 0
+fi
+
+# VMNAME must be set
+if [ -z "${VMNAME+x}" ]
+then
+    echo "You must specify a name for the VM with -n. Use -h to see usage."
+    exit 2
+fi
+
+function fetch_images {
+    case "$DISTRO" in
+        centos7 ) QCOW=CentOS-7-x86_64-GenericCloud.qcow2 ;;
+        centos6 ) QCOW=CentOS-6-x86_64-GenericCloud.qcow2 ;;
+        debian8 ) QCOW=debian-8-20170521-openstack-amd64.qcow2 ;;
+        *       ) usage; exit 2 ;;
+    esac
+
+    mkdir -p ${IMAGEDIR}
+
+    if [ "${DISTRO}" == "centos7" ]
+    then
+        OS_VARIANT="centos7.0"
+        CENTOS7_URL=https://cloud.centos.org/centos/7/images
+        LOGIN_USER=centos
+        if [ ! -f ${IMAGEDIR}/${QCOW} ]
+        then
+            echo "$(date -R) Cloud image not found.  Downloading..."
+            wget -P ${IMAGEDIR} ${CENTOS7_URL}/${QCOW}
+        fi
+    elif [ "${DISTRO}" == "centos6" ]
+    then
+        OS_VARIANT="centos6.9"
+        CENTOS6_URL=https://cloud.centos.org/centos/6/images
+        LOGIN_USER=centos
+        if [ ! -f ${IMAGEDIR}/${QCOW} ]
+        then
+            echo "$(date -R) Cloud image not found.  Downloading..."
+            wget -P ${IMAGEDIR} ${CENTOS6_URL}/${QCOW}
+        fi
+    elif [ "${DISTRO}" == "debian8" ]
+    then
+        OS_VARIANT="debian8"
+        DEBIAN8_URL=https://cdimage.debian.org/cdimage/openstack/current-8
+        LOGIN_USER=debian
+        if [ ! -f ${IMAGEDIR}/${QCOW} ]
+        then
+            echo "$(date -R) Cloud image not found.  Downloading..."
+            wget -P ${IMAGEDIR} ${DEBIAN8_URL}/${QCOW}
+        fi
+    fi
+
+    IMAGE=${IMAGEDIR}/${QCOW}
+}
+
+function check_ssh_key {
+    if [ ! -f "${PUBKEY}" ]
+    then
+        echo "$(date -R) [ERROR] Please generate an SSH keypair using `ssh-keygen -t rsa`"
+        exit 3
     else
-        echo -e "\nNot overwriting $1. Exiting..."
+        KEY=$(<${PUBKEY})
+    fi
+}
+
+# cloud-init variables
+USER_DATA=user-data
+META_DATA=meta-data
+CI_ISO=${VMNAME}-cidata.iso
+
+# Call functions
+check_ssh_key
+fetch_images
+
+# Check if domain already exists
+virsh dominfo ${VMNAME} > /dev/null 2>&1
+
+if [ "$?" -eq 0 ]; then
+    echo -n "[WARNING] ${VMNAME} already exists.  "
+    read -p "Do you want to overwrite ${VMNAME} [y/N]? " -r
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
+        delete_vm ${VMNAME}
+    else
+        echo -e "\nNot overwriting ${VMNAME}. Exiting..."
         exit 1
     fi
 fi
 
-# Directory to store images
-DIR=~/virt/images
-
-# Location of cloud image
-IMAGE=$DIR/CentOS-7-x86_64-GenericCloud.qcow2
-
-# Amount of RAM in MB
-MEM=1024
-
-# Number of virtual CPUs
-CPUS=1
-
-# Disk Size
-RESIZE_DISK=false
-DISK_SIZE=20G
-
-# Cloud init files
-USER_DATA=user-data
-META_DATA=meta-data
-CI_ISO=$1-cidata.iso
-DISK=$1.qcow2
-
-# Bridge for VMs (default on Fedora is virbr0)
-BRIDGE=virbr0
-
 # Start clean
-rm -rf $DIR/$1
-mkdir -p $DIR/$1
+rm -rf ${IMAGEDIR}/${VMNAME}
+mkdir -p ${IMAGEDIR}/${VMNAME}
 
-pushd $DIR/$1 > /dev/null
+pushd ${IMAGEDIR}/${VMNAME} > /dev/null
 
     # Create log file
-    touch $1.log
+    touch ${VMNAME}.log
 
     # cloud-init config: set hostname, remove cloud-init package,
     # and add ssh-key 
     cat > $USER_DATA << _EOF_
 #cloud-config
-
-# Hostname management
-preserve_hostname: False
-hostname: $1
-fqdn: $1.example.local
-
-# Configure where output will go
-output: 
-  all: ">> /var/log/cloud-init.log"
-
-# configure interaction with ssh server
-ssh_genkeytypes: ['ed25519', 'rsa']
-
-# Install my public ssh key to the first user-defined user configured 
-# in cloud.cfg in the template (which is centos for CentOS cloud images)
+package_update: true
+package_upgrade: false
+packages:
+    - less
 ssh_authorized_keys:
-  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBil2QzORhDcnKiVVNpO5daOSYVp8nshcIc7aTEkdlqCRir2Oni8BEStK7x7bvh0jrp9KptlHPeos87fQs//VXEb1FEprL2c6fPWmVdtjmYw3yzSkaFKMksL7FdUoEiwF6t8pQAg2mU0Qj9emSHBKg5ttdGqNoSvXc92k7iOzgauda7jdNak+Dx9dPhR3FJwHMcZSlQHO4cweZcK63bZitxlFkJ/FJdry/TBirDhRcXslOJ3ECU2xiyRXJVPs3VNLjMdOTTAoMmZj+GraUBbQ9VIqe683xe02sM83th5hj2C4gW3qXUoFkNLfKAMRxXLRMEwI3ABFB/AAUhACxyTJp giovanni@throwaway
-
-# Remove cloud-init when finished with it
-#runcmd:
-#  - [ yum, -y, remove, cloud-init ]
+  - ${KEY}
+final_message: "The system is finally up, after $UPTIME seconds."
 _EOF_
 
-    echo "instance-id: $1; local-hostname: $1" > $META_DATA
+##cloud-config
+#
+## Hostname management
+#preserve_hostname: False
+#hostname: ${VMNAME}
+#fqdn: ${VMNAME}.example.local
+#
+## Configure where output will go
+#output: 
+#  all: ">> /var/log/cloud-init.log"
+#
+## configure interaction with ssh server
+#ssh_genkeytypes: ['ed25519', 'rsa']
+#
+## Install my public ssh key to the first user-defined user configured 
+## in cloud.cfg in the template (which is centos for CentOS cloud images)
+#ssh_authorized_keys:
+#  - ${KEY}
+#
+## Remove cloud-init when finished with it
+#runcmd:
+#  - [ yum, -y, remove, cloud-init ]
+#_EOF_
 
-    echo "$(date -R) Copying cloud image..."
+    echo "instance-id: ${VMNAME}; local-hostname: ${VMNAME}" > $META_DATA
+
+    echo "$(date -R) Copying cloud image ($(basename ${IMAGE}))..."
+    DISK=${VMNAME}.qcow2
     cp $IMAGE $DISK
     if $RESIZE_DISK
     then
         echo "$(date -R) Resizing the disk to $DISK_SIZE..."
-        qemu-img create -f qcow2 -o preallocation=metadata $DISK.new $DISK_SIZE >> $1.log 2>&1
-        virt-resize --quiet --expand /dev/sda1 $DISK $DISK.new >> $1.log 2>&1
+        qemu-img create -f qcow2 -o preallocation=metadata $DISK.new $DISK_SIZE >> ${VMNAME}.log 2>&1
+        virt-resize --quiet --expand /dev/sda1 $DISK $DISK.new >> ${VMNAME}.log 2>&1
         mv $DISK.new $DISK
     fi
 
     # Create CD-ROM ISO with cloud-init config
     echo "$(date -R) Generating ISO for cloud-init..."
-    genisoimage -output $CI_ISO -volid cidata -joliet -r $USER_DATA $META_DATA &>> $1.log
+    genisoimage -output $CI_ISO -volid cidata -joliet -r $USER_DATA $META_DATA &>> ${VMNAME}.log
 
     echo "$(date -R) Installing the domain and adjusting the configuration..."
     echo "[INFO] Installing with the following parameters:"
-    echo "    virt-install --import --name $1 --ram $MEM --vcpus $CPUS --disk \
-        $DISK,format=qcow2,bus=virtio --disk $CI_ISO,device=cdrom --network \
-        bridge=virbr0,model=virtio --os-type=linux --os-variant=rhel7 --noautoconsole"
+    echo "    virt-install \\"
+    echo "      --import \\"
+    echo "      --name ${VMNAME} \\"
+    echo "      --ram ${MEMORY} \\"
+    echo "      --vcpus ${CPUS} \\"
+    echo "      --disk $DISK,format=qcow2,bus=virtio \\"
+    echo "      --disk $CI_ISO,device=cdrom \\"
+    echo "      --network bridge=${BRIDGE},model=virtio \\"
+    echo "      --os-type=linux \\"
+    echo "      --os-variant=${OS_VARIANT} \\"
+    echo "      --noautoconsole \\"
 
-    virt-install --import --name $1 --ram $MEM --vcpus $CPUS --disk \
-    $DISK,format=qcow2,bus=virtio --disk $CI_ISO,device=cdrom --network \
-    bridge=virbr0,model=virtio --os-type=linux --os-variant=rhel7 --noautoconsole
+    virt-install --import \
+        --name ${VMNAME} \
+        --ram ${MEMORY} \
+        --vcpus ${CPUS} \
+        --disk $DISK,format=qcow2,bus=virtio \
+        --disk $CI_ISO,device=cdrom \
+        --network bridge=${BRIDGE},model=virtio \
+        --os-type=linux \
+        --os-variant=${OS_VARIANT} \
+        --noautoconsole
 
-    virsh dominfo $1 >> $1.log 2>&1
+    virsh dominfo ${VMNAME} >> ${VMNAME}.log 2>&1
 
     # Eject cdrom
     echo "$(date -R) Cleaning up cloud-init..."
-    virsh change-media $1 hda --eject --config >> $1.log
+    virsh change-media ${VMNAME} hda --eject --config >> ${VMNAME}.log
 
     # Remove the unnecessary cloud init files
-    rm $USER_DATA $META_DATA $CI_ISO
+    ########rm $USER_DATA $META_DATA $CI_ISO
 
-    MAC=$(virsh dumpxml $1 | awk -F\' '/mac address/ {print $2}')
+    MAC=$(virsh dumpxml ${VMNAME} | awk -F\' '/mac address/ {print $2}')
     while true
     do
         IP=$(grep -B1 $MAC /var/lib/libvirt/dnsmasq/$BRIDGE.status | head \
@@ -136,6 +304,6 @@ _EOF_
         fi
     done
 
-    echo "$(date -R) DONE. SSH to $1 using $IP with  username 'centos'."
+    echo "$(date -R) DONE. SSH to ${VMNAME} using $IP with  username '${LOGIN_USER}'."
 
 popd > /dev/null
